import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // Google Fonts import
import "./globals.css"; // Global styles
import Providers from "./Providers"; // Global context/provider wrapper

// Load Geist Sans font and attach to a CSS variable
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"], // Specify character subset to reduce font payload
});

// Load Geist Mono font and attach to a CSS variable
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata config for SEO and page context
export const metadata: Metadata = {
  title: "Create Next App", // Can be dynamically overwritten per page
  description: "Generated by create next app", // Useful for search engines & link previews
};

// Root layout wrapping the entire app
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Strict typing for layout children
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // Apply both font variables globally with antialiasing for smooth text rendering
      >
        <Providers>
          {/* Wraps app with global context/state management (e.g., React Query, Theme, etc.) */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
